#!/usr/bin/env python

from SiamMask.tools.rosdemo import demo_ros_subscriber
import rospy
# from mps_msgs.msg import AABBox2d
import actionlib
from mps_msgs.msg import *

def callback(box):
    rospy.loginfo(rospy.get_caller_id() + "Received: %f %f %f %f", box.xmin, box.ymin, box.xmax, box.ymax)
    demo_ros_subscriber(box)

if __name__== '__main__':
    # In ROS, nodes are uniquely named. If two nodes with the same
    # name are launched, the previous one is kicked off. The
    # anonymous=True flag means that rospy will choose a unique
    # name for our 'listener' node so that multiple listeners can
    # run simultaneously.
    rospy.init_node('BBox_listener', anonymous=True)

    rospy.Subscriber("SiamMask_BBox", AABBox2d, callback)

    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()
