# Begin with a base build
ARG ROS_VERSION=melodic
ARG CUDA_VERSION=10.2-cudnn7-devel-ubuntu18.04

# Begin with a base build
FROM nvidia/cuda:${CUDA_VERSION}
# Initial ARG is outside of build stage, so inherit here
# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG ROS_VERSION

# Set home directory
ENV HOME /root
ENV ROS_DISTRO ${ROS_VERSION}

# Set bash as sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install ROS Baseline
RUN apt-get -yq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -yqq install \
    dirmngr \
    gnupg2 \
    lsb-release && \
    rm -rf /var/lib/apt/lists/*
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get -yq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -yqq install \
    ros-${ROS_VERSION}-ros-base \
    python-rosinstall \
    python-rosinstall-generator \
    python-wstool \
    build-essential && \
    rm -rf /var/lib/apt/lists/*